### ISSUE TITLE
Overlay satellite imagery on elevation data - Associate corresponding positions of terrain and satellite imagery

### ISSUE THREAD

**Issue by jfreemyer** [mtheesen/VRtualize-Pangeo#24]

**Comment by weiluntong** [comment]
Current implementation:

An example Satellite imagery has been pulled and converted into a "material" object for Unity. This can be directly dragged and dropped to be draped onto a terrain object.

**Comment by weiluntong** [comment]
This issue needed to be broken into smaller issues.
